package ro.ase.enums;

public enum Categorie {
    CULINARE, ARTA, ARHITECTURA, ENCICLOPEDII, BIOGRAFII, MEMORII, JURNALE, LINGVISTICA, DICTIONARE, LIMBI_STRAINE,
    POEZIE, TEATRU, STUDII_LITERARE, FICTIUNE, BENZI_DESENATE, GHIDURI_SI_HARTI_TURISTICE, ATLASE, ISTORIE, RELIGIE,
    FILOSOFIE, PSIHOLOGIE, STIINTE_SOCIALE, POLITICA, MARKETING_SI_COMUNICARE, BUSINESS_SI_ECONOMIE, DREPT, MEDICINA,
    STIINTE_EXACTE, MATEMATICI, NATURA_SI_MEDIU, TEHNICA_SI_TEHNOLOGIE, COMPUTERE_SI_INTERNET, SANATATE,
    DEZVOLTARE_PERSONALA, LIFESTYLE, SPORT, TIMP_LIBER, PENTRU_COPII, ADOLESCENTI, ROMANIA, SOFT_EDUCATIONAL
}
